import React from 'react';
import {
  Heart,
  Filter,
  FileText,
  Clock,
  Type,
  Zap,
  Hand,
  ArrowLeftRight,
  SlidersHorizontal,
  Quote,
  Volume2,
  BookOpen,
  Image,
  User,
  CircleHelp,
  Mic,
  Ban,
  Search,
  Folder,
  LayoutGrid,
  Contrast,
  ClockFading,
  Bug,
  Crosshair,
} from 'lucide-react';

export const FEATURES = [
  {
    key: 'favorites',
    label: 'Favoriten',
    description: 'Märchen mit einem Herz markieren und als Favoriten speichern.',
    Icon: () => <Heart size={20} strokeWidth={1.75} />,
  },
  {
    key: 'favorites-only-toggle',
    label: 'Nur Favoriten anzeigen',
    description: 'Schalter in der Seitenleiste, um die Liste auf gespeicherte Favoriten einzuschränken.',
    Icon: () => <Filter size={20} strokeWidth={1.75} />,
  },
  {
    key: 'word-count',
    label: 'Wörteranzahl',
    description: 'Zeigt die Anzahl der Wörter eines Märchens in der Seitenleiste an.',
    Icon: () => <FileText size={20} strokeWidth={1.75} />,
  },
  {
    key: 'reading-duration',
    label: 'Lesezeit',
    description: 'Schätzt die Lesezeit basierend auf 200 Wörtern pro Minute und zeigt sie als „~X min" an.',
    Icon: () => <Clock size={20} strokeWidth={1.75} />,
  },
  {
    key: 'font-size-controls',
    label: 'Schriftgrößen-Steuerung',
    description: 'Plus- und Minus-Schaltflächen in der Kopfzeile zum Anpassen der Schriftgröße.',
    Icon: () => <Type size={20} strokeWidth={1.75} />,
  },
  {
    key: 'pinch-font-size',
    label: 'Pinch-Zoom Schriftgröße',
    description: 'Passt die Schriftgröße per Zwei-Finger-Pinch-Geste im Lesebereich an.',
    Icon: () => <Type size={20} strokeWidth={1.75} />,
  },
  {
    key: 'eink-flash',
    label: 'Seitenumblättern-Effekt',
    description: 'Kurzer Aufblitz beim Blättern - nachempfunden dem Bildschirm eines E-Ink-Lesegeräts.',
    Icon: () => <Zap size={20} strokeWidth={1.75} />,
  },
  {
    key: 'tap-zones',
    label: 'Tipp-Zonen',
    description: 'Unsichtbare Bereiche links und rechts auf der Seite zum Blättern per Fingertipp oder Klick.',
    Icon: () => <Hand size={20} strokeWidth={1.75} />,
  },
  {
    key: 'tap-middle-toggle',
    label: 'Mittige Tipp-Zone zum Ausblenden',
    description: 'Tippen auf die Mitte der Seite blendet die Kopf- und Fußzeile aus (setzt „Tipp-Zonen" voraus).',
    Icon: () => <Hand size={20} strokeWidth={1.75} />,
  },
  {
    key: 'adaption-switcher',
    label: 'Varianten',
    description: 'Dropdown zum Wechseln zwischen der Originalfassung und alternativen Versionen eines Märchens.',
    Icon: () => <ArrowLeftRight size={20} strokeWidth={1.75} />,
  },
  {
    key: 'typography-panel',
    label: 'Typografie-Panel',
    description: 'Einstellbereich für Zeilenhöhe, Textbreite, Zeichenabstand und Schriftart.',
    Icon: () => <SlidersHorizontal size={20} strokeWidth={1.75} />,
  },
  {
    key: 'subscriber-fonts',
    label: 'Erweiterte Schriftarten',
    description: 'Erweitert das Typografie-Panel mit mehr Schriften pro Familie (Serif, Sans, Kursiv) und fügt eine neue Mono-Familie hinzu.',
    Icon: () => <Type size={20} strokeWidth={1.75} />,
  },
  {
    key: 'attribution',
    label: 'Quellenangabe',
    description: 'Zeigt auf der letzten Seite eines Märchens den Autorennamen als Quellenangabe.',
    Icon: () => <Quote size={20} strokeWidth={1.75} />,
  },
  {
    key: 'audio-player',
    label: 'Audio-Player',
    description: 'Zeigt einen eingebetteten Audioplayer an, wenn zum Märchen eine Audiodatei vorhanden ist.',
    Icon: () => <Volume2 size={20} strokeWidth={1.75} />,
  },
  // Gen Alpha
  {
    key: 'read-along',
    label: 'Vorlesen mit Markierung',
    description: 'Liest den Text vor und markiert dabei das aktuelle Wort - ideal für Kinder beim Lesenlernen.',
    Icon: () => <BookOpen size={20} strokeWidth={1.75} />,
  },
  {
    key: 'illustrations',
    label: 'Illustrationen',
    description: 'Zeigt zum Märchen passende Illustrationen an, sofern vorhanden.',
    Icon: () => <Image size={20} strokeWidth={1.75} />,
  },
  {
    key: 'child-profile',
    label: 'Kinderprofil',
    description: 'Separates Leseprofil für Kinder mit vereinfachter Oberfläche und altersgerechten Einstellungen.',
    Icon: () => <User size={20} strokeWidth={1.75} />,
  },
  {
    key: 'story-quiz',
    label: 'Geschichten-Quiz',
    description: 'Einfache Verständnisfragen am Ende eines Märchens - macht das Lesen interaktiv für Kinder.',
    Icon: () => <CircleHelp size={20} strokeWidth={1.75} />,
  },
  // Boomers
  {
    key: 'text-to-speech',
    label: 'Text-zu-Sprache',
    description: 'Liest den Märchentext mit synthetischer Stimme vor - unabhängig von einer aufgenommenen Audiodatei.',
    Icon: () => <Mic size={20} strokeWidth={1.75} />,
  },
  {
    key: 'word-blacklist',
    label: 'Wort-Blacklist',
    description: 'Wörter eintragen, die du nicht lesen möchtest - Märchen mit diesen Wörtern werden in der Seitenleiste ausgeblendet.',
    Icon: () => <Ban size={20} strokeWidth={1.75} />,
  },
  {
    key: 'deep-search',
    label: 'Tiefensuche',
    description: 'Erweitert die Suche von Titeln auf den vollständigen Märchentext (langsamer bei großen Bibliotheken).',
    Icon: () => <Search size={20} strokeWidth={1.75} />,
  },
  // status: Umgesetzt
  {
    key: 'story-directories',
    label: 'Verzeichnisstruktur',
    description: 'Zeigt Geschichten in ihrer Ordnerstruktur an - für Quellen mit regionalen oder thematischen Unterordnern.',
    Icon: () => <Folder size={20} strokeWidth={1.75} />,
  },
  {
    key: 'simplified-ui',
    label: 'Vereinfachte Ansicht',
    description: 'Blendet erweiterte Einstellungen aus und vergrößert Schaltflächen - für eine übersichtlichere, zugänglichere Bedienung.',
    Icon: () => <LayoutGrid size={20} strokeWidth={1.75} />,
  },
  // status: Umgesetzt
  {
    key: 'high-contrast-theme',
    label: 'Hochkontrast-Thema',
    description: 'Fügt dem Themenkreis einen Hochkontrastmodus hinzu - schwarzer Hintergrund mit weißem Text und weißen Rändern für maximale Lesbarkeit.',
    Icon: () => <Contrast size={20} strokeWidth={1.75} />,
  },
  {
    key: 'speed-reader',
    label: 'Schnellleser',
    description: 'Zeigt Wörter einzeln nacheinander in hoher Geschwindigkeit an - zum Training oder für schnelles Erfassen langer Texte.',
    Icon: () => <ClockFading size={20} strokeWidth={1.75} />,
  },
  {
    key: 'debug-badges',
    label: 'Debug-Badges',
    description: 'Zeigt auf jeder Komponente ein Badge mit dem technischen Namen an - für Tester, damit sie immer den richtigen data-testid-Namen kennen.',
    Icon: () => <Bug size={20} strokeWidth={1.75} />,
  },
  // status: Umgesetzt
  {
    key: 'speedreader-orp',
    label: 'ORP-Lesemarke',
    description: 'Hebt den optimalen Erkennungspunkt eines Worts farblich hervor und richtet ihn am Fixationspunkt aus - mit konfigurierbaren Führungslinien.',
    Icon: () => <Crosshair size={20} strokeWidth={1.75} />,
  },
];
